name: pretty_date_time
description: A Dart utility package to convert DateTime objects into human-friendly strings like "5 minutes ago", "Yesterday", or "in 2 days".

version: 0.0.3

homepage: https://github.com/yuvi222/pretty_date_time
repository: https://github.com/yuvi222/pretty_date_time
issue_tracker: https://github.com/yuvi222/pretty_date_time/issues

license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

